spring.application.name=api-gateway
auth_server_url=http://127.0.0.1:8000/.well-known/jwks.json
gateway_url=http://localhost:8080/ 
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
